.\" Process this file with
.\" groff -man -Tascii gnome-globalmenu-manager.1
.\"
.TH gnome-globalmenu-manager 1 "Sep 2011" Linux "User Manuals"
.SH NAME
gnome-globalmenu-manager \- Manager for gnome-globalmenu
.SH DESCRIPTION
.B There is no any options.
.SH AUTHOR
YunQiang Su <wzssyqa@gmail.com>
.SH "SEE ALSO"
.BR gnome-globalmenu (1)
